### ISSUE TITLE
sv_map is unavailable for a few milliseconds on startup as chimera has not populated the map list yet

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/chimera#12]
This breaks using sv_map in init.txt on both the client and the dedicated server.
I also tested this with a script in ui.map, it only works if you sleep for a few ticks first so I assume it is due to Chimera fast loading.

**Comment by Kavawuvi** [comment]
Fixed in https://github.com/Kavawuvi/chimera/commit/b071b493e7e4daaa8a8741d3b874acd3f798a6c4
