### ISSUE TITLE
BINK cinematics playback

### ISSUE THREAD

**Issue by UCyborg** [Kavawuvi/chimera#14]
I put all *.bik files from retail version into the Halo CE root directory. When I use Chimera's strings.dll, nothing plays at startup (as if haloce.exe was invoked with -novideo parameter).

Are only intro cinematics disabled? What about ending.bik? Either way, it'd be nice to have a config setting for this.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/chimera/commit/da335a73be54d9ca3aee25fa5fdabf65175927b2
