### ISSUE TITLE
Add option to configure the font used for player names when targeting them.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/chimera#16]
Chimera can now change the scoreboard font allowing us to use monospace console fonts again, however the font that is used when you aim on another player is still incorrectly tired to the globals "terminal" font reference. We should allow for changing this too, and it should also default to the "multiplayer" HUD globals reference so it looks as intended.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/chimera/commit/6138913fdaa061e4455a01445274073089884cb9
