### ISSUE TITLE
The nav numbers size fix can sometimes cause all numbers to show corrupted due to a race condition.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/chimera#18]
Every time you join an MP game there is a chance the number will be loaded in such a way that the number fix will be acting in reverse and corrupting the numbers rather than causing them to be scaled.

**Comment by Kavawuvi** [comment]
Fixed in https://github.com/Kavawuvi/chimera/commit/6ac12d71111fb55ba733e3804475aaa8b8509622
