### ISSUE TITLE
Allow setting -path in chimera.ini

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/chimera#2]
I think chimera would be useful if you could set -path in chimera.ini This way you could have the game run completely self contained by having a relative path to the profiles without having to always start the game with an argument.

**Comment by gbMichelle** [comment]
If this were done then it should definitely still be overruled if the user uses the -path argument.

**Comment by Kavawuvi** [comment]
chimera.ini now has path overriding. I'll see what I can do about making -path countermand it, but no promises.

**Comment by Kavawuvi** [comment]
Done
