### ISSUE TITLE
where is strings.dll???

### ISSUE THREAD

**Issue by Fallast** [Kavawuvi/chimera#21]
where?

**Comment by Vaporeon** [comment]
If you are talking about builds, there are builds in this forum thread: https://opencarnage.net/index.php?/topic/6916-chimera-10-beta/&page=1

I also have up-to-date builds here: http://vaporeon.io/hosted/halo/chimera/

**Comment by Kavawuvi** [comment]
Going to close this since it doesn't appear to be an actual issue.
