### ISSUE TITLE
Add a "fix" to disable Halo's update check.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/chimera#23]
You can disable the check by editing the UI tags, but if there is a clean way to skip it using an engine mod then perhaps that would be better.

There is no good reason to have the update check enabled.  If a 1.11 update ends up happening despite the very slim chance, you would still be much better off NOT having the game attempt to install it automatically. At this point the mods we all use are much more important than any official update that could potentially be released. There is also the fact Halo Trial never had an update in its entire life.

For these reasons the update check is just a waste of time for people who do not use custom UI's.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/chimera/commit/316173985fee2bf49b775f463bd2956bfd9fbd28
