### ISSUE TITLE
Add queue to enter a server.

### ISSUE THREAD

**Issue by Dark3211** [Kavawuvi/chimera#26]
If it is possible to add queue to enter a server that is full
when there is a free slot (function of HAC 2 or similar).

**Comment by Kavawuvi** [comment]
A queue is a line of players where the player who has waited the longest is allowed to enter the server when a slot is available.

HAC2 doesn't actually add any sort of queue. Rather, it waits for the server to have an open spot before attempting to join, potentially allowing any player in regardless of how long they had waited. At best, the factor that determines if they get to join is their ping to the server versus all other players who were waiting for a spot.

Adding a proper queue would require a server mod, as the server is the only thing that can determine who can or cannot enter.

**Comment by Dark3211** [comment]
Oh Good, Thanks!.
