### ISSUE TITLE
Implement a "chimera_map_info" command.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/chimera#34]
This command could be used to show some information about the currently loaded map in the console.
Some things could be:
- current map name
- current map build string (to show what made it)
- current map size (even show % of buffer used if using maps in RAM
- tag count, tag data usage
- protected status of the map (this check should be exposed to the Lua API too so lua scripts can check if a map is protected before running.)

**Comment by JerryBrick** [comment]
I'm working on it. Here some screenshots:

- <a href="https://i.imgur.com/oaW7T8S.png" target="_blank">ui.map info with maps in RAM enabled</a>
- <a href="https://i.imgur.com/KqbTTqj.png" target="_blank">bigass_mod60.map info with maps in RAM enabled</a>
- <a href="https://i.imgur.com/BlnJdsJ.png" target="_blank">Protected tutorial.map info</a>
- <a href="https://i.imgur.com/WDe09zA.png" target="_blank">ui.map info with maps in RAM disabled</a> (19 fps lol, please bring back the chimera_potato haha)

I have not tested it in the demo version yet.

**Comment by Vaporeon** [comment]
Done in b27044d34310e910589215f2483ec2097b7aaa30
