### ISSUE TITLE
Implement map downloading

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/chimera#4]
Custom maps are not really usable without some kind of automatic downloading of them. There are just too many maps for users to manually manage and unless you are crazy enough to have every possible map installed at once you are highly likely to end up kicked from a custom map server due to not having one of its maps.

Due to hosting costs and management time needed to maintain a repo, I think it would be pragmatic to just use the existing HAC2 repo, as much as it has problems it does not seem like it is going anywhere in a hurry.

**Comment by Kavawuvi** [comment]
Done
