### ISSUE TITLE
Custom Chat will render in a weird way when certain characters are in player names.

### ISSUE THREAD

**Issue by gbMichelle** [Kavawuvi/chimera#6]
When some characters are in player names the text will move back to the beginning of the line, causing text to be overlapped.

I assume this has something to do with the converting of the text from utf-16 to utf-8 having some overlap for special characters.

I'm thinking the easiest solution would be to set a range for allowed characters and prune everything outside of that.

**Comment by Kavawuvi** [comment]
I think I fixed the issue in https://github.com/Kavawuvi/chimera/commit/6ef0f68a05e1bb78e8ade443f102ca1f2fedec45?
![image](https://user-images.githubusercontent.com/39858815/81739542-27e0bd80-9461-11ea-9fe4-dcca0a1eb0b7.png)
